language: node_js
node_js:
  - "8"
  - "7"
  - "6"
notifications:
  email: "markusgilg@outlook.de"

jobs:
  include:
  - stage: test
    script: npm test
  - stage: deploy
    if: branch = master
    node_js: "8"
    script: npm publish && npm coverage
